### ISSUE TITLE
error when use in angular2 version  2.4.6 

### ISSUE THREAD

**Issue by wqdjl** [NepipenkoIgor/ng2-mask#18]
"Error: Can't resolve all parameters for MaskDirective: ([object Object], ?).
    at SyntaxError.ZoneAwareError (http://0004.saas.com:6999/polyfills.bundle.js:9956:33)
    at SyntaxError.BaseError [as constructor] (http://0004.saas.com:6999/vendor.bundle.js:94487:16)
    at new SyntaxError (http://0004.saas.com:6999/vendor.bundle.js:11305:16)
    at CompileMetadataResolver._getDependenciesMetadata (http://0004.saas.com:6999/vendor.bundle.js:24884:31)
    at CompileMetadataResolver._getTypeMetadata (http://0004.saas.com:6999/vendor.bundle.js:24759:26)
    at CompileMetadataResolver.getNonNormalizedDirectiveMetadata (http://0004.saas.com:6999/vendor.bundle.js:24399:24)
    at CompileMetadataResolver._loadDirectiveMetadata (http://0004.saas.com:6999/vendor.bundle.js:24275:23)
    at http://0004.saas.com:6999/vendor.bundle.js:24476:54
    at Array.forEach (native)
    at CompileMetadataResolver.loadNgModuleDirectiveAndPipeMetadata (http://0004.saas.com:6999/vendor.bundle.js:24475:41)
    at http://0004.saas.com:6999/vendor.bundle.js:59902:58
    at Array.forEach (native)
    at JitCompiler._loadModules (http://0004.saas.com:6999/vendor.bundle.js:59901:43)
    at JitCompiler._compileModuleAndComponents (http://0004.saas.com:6999/vendor.bundle.js:59856:52)
    at JitCompiler.compileModuleAsync (http://0004.saas.com:6999/vendor.bundle.js:59822:21)"

**Comment by victorschinaider** [comment]
Are you using angular cli?

**Comment by erickkenji** [comment]
got the same error

**Comment by victorschinaider** [comment]
@erickkenji, could you give us more details? Ara you using angular cli? What version? What version of Angular are you using?

**Comment by victorschinaider** [comment]
@erickkenji, and could provide us with some code of the input, and the AngularModule that the component is inside of?

**Comment by wqdjl** [comment]
@victorschinaider    "angular-cli": "1.0.0-beta.28.3",

**Comment by wqdjl** [comment]
compiling error : 
ERROR in Error encountered resolving symbol values statically. Calling function 'ɵmakeDecorator', function calls
are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving
symbol NgModule in E:/saas/Code/Phoenix2.0/node_modules/ng2-mask/node_modules/@angular/core/core.d.ts, resolving
symbol Ng2MaskModule in E:/saas/Code/Phoenix2.0/node_modules/ng2-mask/build/ng2-mask.module.d.ts, resolving symbo
l Ng2MaskModule in E:/saas/Code/Phoenix2.0/node_modules/ng2-mask/build/ng2-mask.module.d.ts

**Comment by wqdjl** [comment]
It could be for this reason,
![image](https://cloud.githubusercontent.com/assets/14515076/26663037/a95e84de-46ba-11e7-8e53-ccb2ab6ecb01.png)

**Comment by wqdjl** [comment]
@victorschinaider  could you help me

**Comment by NepipenkoIgor** [comment]
In my opinion you should use actual version not beta.

**Comment by wqdjl** [comment]
upgrade cli : "@angular/cli": "^1.1.0",
but error not repair 
![image](https://cloud.githubusercontent.com/assets/14515076/26671523/63a66f96-46e8-11e7-82c1-d30783005346.png)

**Comment by wqdjl** [comment]
"Error: Unexpected value 'Ng2MaskModule' imported by the module 'PhoenixCommonModule'
    at SyntaxError.ZoneAwareError (http://0004.saas.com:4999/polyfills.bundle.js:30263:33)
    at SyntaxError.BaseError [as constructor] (http://0004.saas.com:4999/vendor.bundle.js:15876:16)
    at new SyntaxError (http://0004.saas.com:4999/vendor.bundle.js:35698:16)
    at http://0004.saas.com:4999/vendor.bundle.js:21584:44
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://0004.saas.com:4999/vendor.bundle.js:21569:49)
    at CompileMetadataResolver.getNgModuleSummary (http://0004.saas.com:4999/vendor.bundle.js:21511:52)
    at http://0004.saas.com:4999/vendor.bundle.js:21582:72
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://0004.saas.com:4999/vendor.bundle.js:21569:49)
    at CompileMetadataResolver.getNgModuleSummary (http://0004.saas.com:4999/vendor.bundle.js:21511:52)
    at http://0004.saas.com:4999/vendor.bundle.js:21582:72
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (http://0004.saas.com:4999/vendor.bundle.js:21569:49)
    at CompileMetadataResolver.getNgModuleSummary (http://0004.saas.com:4999/vendor.bundle.js:21511:52)"

**Comment by wqdjl** [comment]
![image](https://cloud.githubusercontent.com/assets/14515076/26672621/637e571e-46ec-11e7-9fb0-e43363e2c0da.png)
the error can repair when upgrade ts

**Comment by wqdjl** [comment]
ng2-mask can not use in angular 2.XX
because Renderer2 not in angular 2.XX, and MaskDirective use Renderer2

**Comment by wqdjl** [comment]
@erickkenji

**Comment by victorschinaider** [comment]
@wqdjl , i think we can modify to old Renderer for now.

**Comment by NepipenkoIgor** [comment]
@victorschinaider In my opinion we should use last version  ( Google way ) . But if it is issue important for community we should change it for old. Could You do this as hot fix ?

**Comment by Sevensnake** [comment]
on textbox load object data or send to textbox I get this.
ERROR Error: Uncaught (in promise): TypeError: inputValue.split is not a function
TypeError: inputValue.split is not a function
    at MaskDirective._applyMask (mask.directive.js:94)
    at MaskDirective.writeValue (mask.directive.js:72)

**Comment by NepipenkoIgor** [comment]
@Sevensnake related to #20

**Comment by NepipenkoIgor** [comment]
@wqdjl ,@erickkenji Could you check update ??
